### ISSUE TITLE
'look'  and 'look masterBedroom' commands when in masterBedroom return parser error

### ISSUE THREAD

**Issue by LeBrendanJames** [kniers/Capstone#1]
I think these commands need to return the long description of the room. Funnily enough, 'look around' works fine.

**Comment by kniers** [comment]
Not recognizing the current room is a bug in PyEngine. For "look", I think it should just bypass the text parser and look at the current room. I'll fix both of these

**Comment by zurbrugc** [comment]
It would be easier if commands such as "look", "help", and "exit" were checked before sending the command to the parser. I can add them if necessary, but it would just be putting the same string into a Command to be checked in the same way.

**Comment by kniers** [comment]
Fixed. High level command including look and help are handled in game.cpp without the text parser. PyEngine was fixed to recognize the current room.
