### ISSUE TITLE
Butler is bugged

### ISSUE THREAD

**Issue by zurbrugc** [kniers/Capstone#5]
Attempting to interact with the butler in any way causes the game to crash with a "Error! Room not found" message

**Comment by LeBrendanJames** [comment]
Fixed, I believe, with commit https://github.com/kniers/Capstone/commit/2ce5c1b6c05581f468a85824642ab03a625913a9. Some of the verbs to interact with the butler were looking into the properties dictionary incorrectly.

Leaving open until we can confirm all of the verbs work. I just tested a few based on one play through.

**Comment by zurbrugc** [comment]
I pushed a bunch of bug fixes, some related, some not. The butler does what he's supposed to now.
